### ISSUE TITLE
Release v0.1.9

### ISSUE THREAD

**Issue by strohel** [cameleon-rs/cameleon#159]
Hi @Y-Nak, with recent little tweaks merged, a new patch cameleon release would be useful for us.

Perhaps me or @bschwind can try doing that to learn the process? Do you do `cargo release` and/or some extra steps? How does changelog extraction from PRs work?

**Comment by Y-Nak** [comment]
Hi @strohel,
Yes, it's nice timing to cut a new release. And I'm happy to share the process with you and appreciate your help.

## Release process
### 1. Publish
1. Bump up all the crate versions in the workspace using `cargo set-version --bump patch` https://github.com/killercup/cargo-edit#cargo-set-version.
2. Publish the crates with `cargo release`
3. Open a PR to reflect the changes.

### 2. Changelog
1. Create a new release on the GitHub page.
2. Create a tag.
3. Use [automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) and modify it *manually*

About 3, I used a small ugly Python script initially to extract the `[ChangeLog` section. 
But I realized I have to categorize changes manually, and the maintenance cost of the script exceeds the manual modification cost 😅. So I settled down the current process.

The process was not so troublesome because I was the only one who managed the release, and there were not so many changes often. But yeah, it'd be nice timing to consider using CI for release automation.

**Comment by strohel** [comment]
@Y-Nak thanks!

> Bump up all the crate versions in the workspace using cargo set-version --bump patch https://github.com/killercup/cargo-edit#cargo-set-version.

It looks like `cargo release` now also does this? Specifically its `cargo release version patch` subcommand.

> Create a tag.

I see that for v0.1.8 there is a tag for each crate, i.e. `cameleon-genapi-v0.1.8`, `cameleon-impl-v0.1.8`, while for earlier releases, only `cameleon-v0.1.8` was made. Apparently `cargo release` wants to do the former by default.

Which of the 2 approaches is preferred?

Creating a single tag might feel more organized over time, and a config to `cargo publish` can be created to only tag `cameleon-vX.Y.Z`

> Use [automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) and modify it manually

Wow, today I learned that one can configure custom sections and associated labels for PRs in `.github/release.yml` for GitHub to sort them automatically.

**Comment by Y-Nak** [comment]
> Wow, today I learned that one can configure custom sections and associated labels for PRs in .github/release.yml for GitHub to sort them automatically.

Yeah, it'd be nice to switch to a label-based changelog from the current `Changelog` way.

> Which of the 2 approaches is preferred?

+1 for generating a single tag for all crates like `cameleon-v0.1.9`.

**Comment by strohel** [comment]
Okay, the release is published and visible in https://github.com/cameleon-rs/cameleon/releases/tag/cameleon-v0.1.9

Feel free to tweak the notes as you see fit.

**Comment by strohel** [comment]
I've removed 2 changelog items that already went into 0.1.8 - GitHub somehow generated changelog from 0.1.**7**..0.1.9 and I didn't notice.
